### ISSUE TITLE
File corruption

### ISSUE THREAD

**Issue by HuangdaLiu** [keystone-enclave/keystone#100]
Firesim-riscv-tools-prebuilt  was damaged when I unzipped it.
    Thank you!

**Comment by dkohlbre** [comment]
Hm. It likely got truncated in transit or otherwise mangled, its not been changed on the hosting end.

We can add an integrity check possibly, but for now I suggest re-downloading.

**Comment by dkohlbre** [comment]
OK, it looks like github isn't serving the file for the 1.0 tools correctly anymore. (2.0 seems fine)
This appears to be an issue on github's file serve end, not sure why. (We're seeing connections dropped most of the way through download)

expected sha256sum for the files are as follows.

$ sha256sum 1.0.zip 
40148ac9cc12af1d77713e7bd9ba5c865aa708c17d3d2983eef3b3f286a27827  1.0.zip
$ sha256sum 2.0.tar.gz 
bdc9e3ec47ac461ecc7865609fda6b820439c36130e9da9275af010d9f4fe4bc  2.0.tar.gz


You can try using the 1.0.zip tools, which appears to be doing OK.

**Comment by dkohlbre** [comment]
Github file-serving issue appears to have cleared up. 1.0.tar.gz is now serving correctly.
(sha256sum 05211edea5a47ebaf906ef4bed2c9609a93e8c6ad5e45f8c87678eabbfd424e7 )

Closing for now, since there isn't much we can do about it.
