### ISSUE TITLE
解压异常，fast-setup.sh运行出错

### ISSUE THREAD

**Issue by justDoForever** [keystone-enclave/keystone#106]
firesim-riscv-tools-prebuilt-2.0/distrib.tar.partbn
firesim-riscv-tools-prebuilt-2.0/distrib.tar.partbo
firesim-riscv-tools-prebuilt-2.0/distrib.tar.partbp
firesim-riscv-tools-prebuilt-2.0/distrib.tar.partbq

gzip: stdin: unexpected end of file
tar: 归档文件中异常的 EOF
tar: 归档文件中异常的 EOF
tar: Error is not recoverable: exiting now
./fast-setup.sh: 行 33: ./installrelease.sh: 没有那个文件或目录
mv: 无法获取'distrib' 的文件状态(stat): 没有那个文件或目录
cp: 无法获取'riscv' 的文件状态(stat): 没有那个文件或目录
Toolchain has been installed in /home/whch/keystone/riscv

**Comment by mssun** [comment]
I don't have this issue. I suspect that you failed to download the prebuilt firesim-riscv toolchains.

**Comment by dkohlbre** [comment]
We've been having problems with github serving corrupted binaries for the toolchain before, it may be happening again.

Did the sha integrity check pass?
`sha256sum -c .prebuilt_tools_shasums --status --ignore-missing`
in the fast-setup.sh

**Comment by justDoForever** [comment]
> I don't have this issue. I suspect that you failed to download the prebuilt firesim-riscv toolchains.

Yes,it's right.But it is always download failed.

HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/x-gzip]
Saving to: '1.0.tar.gz.1’

1.0.tar.gz.1            [              <=>   ]   1.01G   213KB/s    in 11m 45s 

2019-07-27 20:37:05 (1.47 MB/s) - Read error at byte 1085176112 (Success).Retrying.

HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/x-gzip]
Saving to: '2.0.tar.gz’

2.0.tar.gz              [               <=>  ]   1.01G  3.46MB/s    in 9m 14s  

2019-07-27 21:15:33 (1.87 MB/s) - Read error at byte 1086238332 (Success).Retrying.

HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/x-gzip]
Saving to: '2.0.tar.gz’

2.0.tar.gz              [  <=>               ] 948.93M  1.90MB/s    in 8m 32s  

2019-07-27 21:56:55 (1.85 MB/s) - Read error at byte 1086238332 (Success).Retrying.

HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/x-gzip]
Saving to: '2.0.tar.gz’

2.0.tar.gz              [            <=>     ]   1.03G  2.79MB/s    in 8m 7s   

2019-07-27 22:27:11 (2.17 MB/s) - Read error at byte 1110683260 (Success).Retrying.

HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/x-gzip]
Saving to: '2.0.tar.gz’

2.0.tar.gz              [                <=> ]   1.02G  2.02MB/s    in 11m 22s 

2019-07-27 23:01:07 (1.53 MB/s) - Read error at byte 1110683260 (Success).Retrying.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/x-gzip]
Saving to: '2.0.tar.gz’

2.0.tar.gz              [        <=>         ]   1.01G  1.77MB/s    in 11m 9s  

2019-07-28 11:59:44 (1.55 MB/s) - Read error at byte 1085991196 (Success).Retrying.

HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/x-gzip]
Saving to: '2.0.tar.gz’

2.0.tar.gz                 [                        <=> ]   1.02G  2.44MB/s    in 12m 4s  

2019-07-28 12:20:19 (1.44 MB/s) - Read error at byte 1092361792 (Success).Retrying.

HTTP request sent, awaiting response... 200 OK
Length: 1202303660 (1.1G) [application/x-gzip]
Saving to: '2.0.tar.gz’

2.0.tar.gz              90%[========================>   ]   1.01G  2.42MB/s    in 15m 1s  

2019-07-28 12:35:21 (1.15 MB/s) - Connection closed at byte 1092361792. Retrying.


I am so tired. .......................

**Comment by dkohlbre** [comment]
Yeah, this is an issue we've seen before. It will happen for a day or two, github just fails to serve the file sometimes. There is nothing we can do about it immediately.

We will (this week hopefully) be moving the pre-built toolchains off of github, and on-to our own hosting.

For now, you can build the toolchain locally, rather than download prebuilt ones. (See the setup.sh and http://docs.keystone-enclave.org/en/dev/Getting-Started/QEMU-Setup-Repository.html#manual-setup )
Let us know if you run into issues with that.

**Comment by justDoForever** [comment]
Ok,thank you very much.I am trying it with another way now.------------------ 原始邮件 ------------------
发件人: "dkohlbre"<notifications@github.com>
发送时间: 2019年7月30日(星期二) 中午11:39
收件人: "keystone-enclave/keystone"<keystone@noreply.github.com>;
抄送: "justDoForever"<1412317359@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [keystone-enclave/keystone] 解压异常，fast-setup.sh运行出错 (#106)



Yeah, this is an issue we've seen before. It will happen for a day or two, github just fails to serve the file sometimes. There is nothing we can do about it immediately.
 
We will (this week hopefully) be moving the pre-built toolchains off of github, and on-to our own hosting.
 
For now, you can build the toolchain locally, rather than download prebuilt ones. (See the setup.sh and http://docs.keystone-enclave.org/en/dev/Getting-Started/QEMU-Setup-Repository.html#manual-setup )
 Let us know if you run into issues with that.
 
&mdash;

**Comment by dkohlbre** [comment]
Closing this as the commits in #110 now have new hosting for the toolchain that isn't on github.
See issue #107 for further discussion as needed.
