### ISSUE TITLE
ncurses 6.1 Configuring failed:configure: error: C compiler cannot create executables

### ISSUE THREAD

**Issue by justDoForever** [keystone-enclave/keystone#107]
whch@whch:~/keystone$ make
mkdir -p buildroot/dl
make -f hifive.mk
make[1]: Entering directory '/home/whch/keystone'
make -s -C /home/whch/keystone/buildroot RISCV=/home/whch/keystone/riscv-gnu-toolchain/riscv PATH=/home/whch/keystone/riscv-gnu-toolchain/riscv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/whch/keystone/riscv-gnu-toolchain/riscv/bin O=/home/whch/keystone/hifive-work/buildroot_initramfs
make[2]: Entering directory '/home/whch/keystone/buildroot'
>>> ncurses 6.1 Configuring
configure: error: C compiler cannot create executables
make[2]: *** [package/pkg-generic.mk:231: /home/whch/keystone/hifive-work/buildroot_initramfs/build/ncurses-6.1/.stamp_configured] Error 77
make[2]: Leaving directory '/home/whch/keystone/buildroot'
make[1]: *** [hifive.mk:62: /home/whch/keystone/hifive-work/buildroot_initramfs/images/rootfs.tar] Error 2
make[1]: Leaving directory '/home/whch/keystone'
make: *** [Makefile:18: hifive] Error 2

Thank you for answer,may be it's not a bug.

**Comment by dkohlbre** [comment]
Buildroot is failing to build because it cannot build RISC-V binaries.

There are a couple things that could be going wrong, but if haven't modified any configs the most likely answer is:
You don't have a complete RISC-V toolchain built/available on path (ie: do you have a working RISC-V gcc in /home/whch/keystone/riscv-gnu-toolchain/riscv/bin)

Can you test the RISC-V gcc to ensure that it works?

**Comment by justDoForever** [comment]
> Buildroot is failing to build because it cannot build RISC-V binaries.
> 
> There are a couple things that could be going wrong, but if haven't modified any configs the most likely answer is:
> You don't have a complete RISC-V toolchain built/available on path (ie: do you have a working RISC-V gcc in /home/whch/keystone/riscv-gnu-toolchain/riscv/bin)
> 
> Can you test the RISC-V gcc to ensure that it works?

How to test  the RISC-V gcc ? I try it as the following:
 
whch@whch:~/keystone$ echo -e '#include <stdio.h>\n int main(void) { printf("Hello world!\\n"); return 0; }' > hello.c
whch@whch:~/keystone$ riscv64-unknown-elf-g
riscv64-unknown-elf-g++         riscv64-unknown-elf-gcov
riscv64-unknown-elf-gcc         riscv64-unknown-elf-gcov-dump
riscv64-unknown-elf-gcc-7.2.0   riscv64-unknown-elf-gcov-tool
riscv64-unknown-elf-gcc-ar      riscv64-unknown-elf-gdb
riscv64-unknown-elf-gcc-nm      riscv64-unknown-elf-gprof
riscv64-unknown-elf-gcc-ranlib  
whch@whch:~/keystone$ riscv64-unknown-elf-gcc -o hello hello.c
whch@whch:~/keystone$ spike pk hello

Command 'spike' not found, did you mean:

  command 'spine' from deb cacti-spine (1.2.1-1)
  command 'spipe' from deb spiped (1.6.0-4)

Try: sudo apt install <deb name>


Is it right?

**Comment by dkohlbre** [comment]
If `riscv64-unknown-elf-gcc` creates a RISC-V binary (`file hello` returns a RISC-V 64 bit binary) then it should be working fine. No need to test it in `spike`.

Can you give the output of `echo $RISCV`, and `which riscv64-unknown-elf-gcc`? I suspect this is a PATH issue more than anything else.

Do you have any modifications made to the Makefiles, source configs, etc?

**Comment by justDoForever** [comment]
> If `riscv64-unknown-elf-gcc` creates a RISC-V binary (`file hello` returns a RISC-V 64 bit binary) then it should be working fine. No need to test it in `spike`.
> 
> Can you give the output of `echo $RISCV`, and `which riscv64-unknown-elf-gcc`? I suspect this is a PATH issue more than anything else.
> 
> Do you have any modifications made to the Makefiles, source configs, etc?

I do it as you said,

whch@whch:~/keystone/riscv-gnu-toolchain$ echo $RISCV
**/home/whch/keystone/riscv-gnu-toolchain/riscv**
whch@whch:~/keystone/riscv-gnu-toolchain$ which riscv64-unknown-elf-gcc
**/home/whch/keystone/riscv-gnu-toolchain/riscv/bin/riscv64-unknown-elf-gcc**
whch@whch:~/keystone/riscv-gnu-toolchain$ 

I don't have any modifications made to the Makefiles and source configs.
I followed the tutorial step by step. the tutorial website is : 
https://docs.keystone-enclave.org/en/latest/Getting-Started/Running-Keystone-with-QEMU.html

**Comment by dayeol** [comment]
I'm not 100% sure, but I have seen this when I was building buildroot from ilp32 instead of ilp32d. Could be an issue of hardfloat/softfloat in the toolchain. How did you obtain the toolchain? Have you configured/built the toolchain by yourself, or did you downloaded it using `fast-setup.sh`?

**Comment by justDoForever** [comment]
Thank you for answer.I have built the toolchain by myself,because I failed to build the toolchains by the ./fast-up.sh.Can we download the 2.0.tar.gz through your own server now ?------------------ 原始邮件 ------------------
发件人: "Dayeol Lee"<notifications@github.com>
发送时间: 2019年8月4日(星期天) 中午11:51
收件人: "keystone-enclave/keystone"<keystone@noreply.github.com>;
抄送: "justDoForever"<1412317359@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [keystone-enclave/keystone] ncurses 6.1 Configuringfailed:configure: error: C compiler cannot create executables (#107)



I'm not 100% sure, but I have seen this when I was building buildroot from ilp32 instead of ilp32d. Could be an issue of hardfloat/softfloat in the toolchain. How did you obtain the toolchain? Have you configured/built the toolchain by yourself, or did you downloaded it using fast-setup.sh?
 
&mdash;

**Comment by dayeol** [comment]
Can you check if github file serving is back to normal?
We might need to test before we serve the zip file through our own server, but we can't work on that at this moment.
If you are building the toolchain by yourself, I recommend you to use `setup.sh`.

**Comment by dayeol** [comment]
We have started to serve the files from our own server.
Can you open up the `fast-setup.sh` and replace following line
```
wget https://github.com/keystone-enclave/firesim-riscv-tools-prebuilt/archive/${TOOL_VER}.tar.gz``` 
with
```
wget http://keystone-enclave.eecs.berkeley.edu/files/${TOOL_VER}.tar.gz
```

**Comment by dayeol** [comment]
We figured out that the following document was wrong.

```
cd riscv-gnu-toolchain
./configure --prefix=$(pwd)/riscv --enable-multilib
make; make linux
```

You should not use `--enable-multilib` when configuring the toolchain,
and also the prefix is wrong. it was supposed to be

```
cd riscv-gnu-toolchain
./configure --prefix=$(pwd)/../riscv 
make; make linux
```

Will be fixed with #110

**Comment by dkohlbre** [comment]
the commits in #110 have corrected the fast-setup issues and the documentation for building the toolchain manually.

It won't land on `master` for a while due to some known SDK issues.
You can manually update the fetch URL in fast-setup (as the commit does) or rebuild your toolchain with the new instructions in the `dev` docs (http://docs.keystone-enclave.org/en/dev/Getting-Started/QEMU-Setup-Repository.html)

Let us know if one of these works for you.

**Comment by justDoForever** [comment]
Ok,thank your team very much.I'll try again.------------------ 原始邮件 ------------------
发件人: "Dayeol Lee"<notifications@github.com>
发送时间: 2019年8月11日(星期天) 凌晨2:29
收件人: "keystone-enclave/keystone"<keystone@noreply.github.com>;
抄送: "justDoForever"<1412317359@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [keystone-enclave/keystone] ncurses 6.1 Configuringfailed:configure: error: C compiler cannot create executables (#107)



We figured out that the following document was wrong.
 cd riscv-gnu-toolchain ./configure --prefix=$(pwd)/riscv --enable-multilib make; make linux  
You should not use --enable-multilib when configuring the toolchain,
 and also the prefix is wrong. it was supposed to be
 cd riscv-gnu-toolchain ./configure --prefix=$(pwd)/../riscv  make; make linux  
Will be fixed with #110
 
&mdash;

**Comment by normandyfrance** [comment]
> Ok,thank your team very much.I'll try again.------------------ 原始邮件 ------------------ 发件人: "Dayeol Lee"<notifications@github.com> 发送时间: 2019年8月11日(星期天) 凌晨2:29 收件人: "keystone-enclave/keystone"<keystone@noreply.github.com>; 抄送: "justDoForever"<1412317359@qq.com>;"Author"<author@noreply.github.com>; 主题: Re: [keystone-enclave/keystone] ncurses 6.1 Configuringfailed:configure: error: C compiler cannot create executables (#107) We figured out that the following document was wrong. cd riscv-gnu-toolchain ./configure --prefix=$(pwd)/riscv --enable-multilib make; make linux You should not use --enable-multilib when configuring the toolchain, and also the prefix is wrong. it was supposed to be cd riscv-gnu-toolchain ./configure --prefix=$(pwd)/../riscv make; make linux Will be fixed with #110 &mdash; You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

Could you please tell me how is it going? I came across the same problem as yours. Was the solution effective?

**Comment by dayeol** [comment]
@justDoForever, Please tell us back if the fix did not work. Otherwise, you can close the issue

**Comment by dayeol** [comment]
Supposed to be fixed now. Closing
