### ISSUE TITLE
ncurses 6.1 Configuring configure: error: C compiler cannot create executables

### ISSUE THREAD

**Issue by normandyfrance** [keystone-enclave/keystone#109]
I tryed to use fast-setup first, but it didn't work. After that  I saw your discussion. Then I turned to manual setup. Although the process was very slow and difficult, it completed and it reached to 1.2.1.3.1. Build All. I used "make" first and I came across the problem.

### 
$make 
mkdir -p buildroot/dl
make -f hifive.mk
make[1]: Entering directory '/home/gw/keystone'
make -s -C /home/gw/keystone/buildroot RISCV=/home/gw/keystone/riscv-gnu-toolchain/riscv PATH=/home/gw/keystone/riscv-gnu-toolchain/riscv/bin:/home/gw/bin:/home/gw/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:home/keystone/riscv/bin:/home/gw/keystone/riscv-gnu-toolchain/riscv/bin O=/home/gw/keystone/hifive-work/buildroot_initramfs
make[2]: Entering directory '/home/gw/keystone/buildroot'
>>> ncurses 6.1 Configuring
configure: error: C compiler cannot create executables
package/pkg-generic.mk:228: recipe for target '/home/gw/keystone/hifive-work/buildroot_initramfs/build/ncurses-6.1/.stamp_configured' failed
make[3]: *** [/home/gw/keystone/hifive-work/buildroot_initramfs/build/ncurses-6.1/.stamp_configured] Error 77
Makefile:84: recipe for target '_all' failed
make[2]: *** [_all] Error 2
make[2]: Leaving directory '/home/gw/keystone/buildroot'
hifive.mk:62: recipe for target '/home/gw/keystone/hifive-work/buildroot_initramfs/images/rootfs.tar' failed
make[1]: *** [/home/gw/keystone/hifive-work/buildroot_initramfs/images/rootfs.tar] Error 2
make[1]: Leaving directory '/home/gw/keystone'
Makefile:17: recipe for target 'hifive' failed
make: *** [hifive] Error 2
### 
Then I tried to use "sudo make" , the result was:

$sudo make
mkdir -p buildroot/dl
make -f hifive.mk
make[1]: Entering directory '/home/gw/keystone'
make[1]: *** No rule to make target '/home/gw/keystone/riscv/bin/riscv64-unknown-linux-gnu-gcc', needed by '/home/gw/keystone/hifive-work/buildroot_initramfs/images/rootfs.tar'。 停止。
make[1]: Leaving directory '/home/gw/keystone'
Makefile:17: recipe for target 'hifive' failed
make: *** [hifive] Error 2

Could you please tell me how to deal with the problem?

**Comment by dayeol** [comment]
could you provide followings

(1) Results of `git submodule status`
(2) Your Linux distribution (e.g., Ubuntu 14.04)
(3) The branch you're working on (e.g., `master` or `dev`)

**Comment by dayeol** [comment]
We started to host the prebuilt toolchain from our own server.
Could you refer to #107, modify `fast-setup.sh` and try again?
You might need to move the RISC-V toolchain you've built to avoid overwritting.

**Comment by dayeol** [comment]
Duplicated issue, closing.
Please see #107 for further updates
