### ISSUE TITLE
Travis script fails due to system lack of memory.

### ISSUE THREAD

**Issue by ThaumicMekanism** [keystone-enclave/keystone#123]
I was trying to run the travis tests to validate the install and it was erroring without giving the real reason (just my suspicion that it did not launch qemu for some reason). I dug around and found out it was because I allocated my system with too little memory. Do you think we can add a check to give a proper error message about that or forward the error message to the travis script so that users can realize that they may need to allocate more memory for qemu to properly boot?

**Comment by dayeol** [comment]
In such case, QEMU error message should have been shown up saying that QEMU failed to start because of too small memory. What was the error  log like when you first tried?

**Comment by ThaumicMekanism** [comment]
Hmm. I actually forgot to check the error log. I expected a message to be outputted to terminal for a fail such as that.

**Comment by dayeol** [comment]
Travis has been working okay. Closing the issue. Please reopen when we need any action
