### ISSUE TITLE
Build system attempts repatch/rebuild on every make

### ISSUE THREAD

**Issue by dkohlbre** [keystone-enclave/keystone#138]
Currently, when running `make` we attempt to:
reapply patches to Linux
reapply patches to qemu
re-configure/build qemu

We should only do these operations when required.

**Comment by dayeol** [comment]
This was actually intended to be safe. 
There were multiple cases where people wanted to just bump or recompile linux/qemu but then
missed patch because they were only applied at first setup, and then that caused problems.

What would be the other place that you'd put them?

**Comment by dayeol** [comment]
Fixing "reconfiguring qemu" .

**Comment by dkohlbre** [comment]
I think its fine to have these in the main cmake. The problem is that it attempts to reapply them on every build. If we've applied the patch already, there is no valid way to try and apply an updated patch (given the way we currently do things.) 

The patch application should be a build dependency for the qemu/linux build so that its only done if we haven't finished building. (This won't be the right thing 100% of the time, we could use a . file to mark it if we really wanted, but it should be OK)

**Comment by dayeol** [comment]
Okay, then separating the patch target from the build would resolve this issue in that case.
But that will also require people to explicitly run patch commands at first build.
I'm trying to understand what is a big problem with this, if you want to try and apply and updated patch, how often will you need that and why can't you do that with the way we currently do things?

**Comment by dayeol** [comment]
removing "ALL" from qemu-config rule may help. let me try that.
