### ISSUE TITLE
Only 2GB RAM available on HiFive Unleashed

### ISSUE THREAD

**Issue by thechristschn** [keystone-enclave/keystone#148]
**Describe the bug**
After booting current master on the HiFive Unleashed Board, there are only 2GB RAM available.

According to SiFive, the Board should have 8GB RAM.

**Screenshots or Error Log**
```
# free
              total        used        free      shared  buff/cache   available
Mem:        1988464       15624     1967948        4892        4892     1962520
Swap:             0           0           0
```

**Comment by dayeol** [comment]
Please refer to the following comment: 
https://github.com/keystone-enclave/keystone/issues/147#issuecomment-592246477

**Comment by dayeol** [comment]
This will be fixed with the OpenSBI port.
The cause was the wrong device tree being passed.

with OpenSBI:
```
# free
              total        used        free      shared  buff/cache   available
Mem:        8183984       67084     8090564       26336       26336     8042240
Swap:             0           0           0
```

**Comment by dayeol** [comment]
Resolved
