### ISSUE TITLE
Is it possible to erase a specified data in Secure Monitor(SM) by passing an address in Eapp address space?

### ISSUE THREAD

**Issue by Kenun99** [keystone-enclave/keystone#149]
I want to extend an erase function call in Secure Monitor(SM)  in order to clean a specified memory of EApp.

If I'd declared a sensitive data(Sdata) in EApp , and then packed it with the Host to Run in the Keystone Paltform, how can I erase this data. 

Now I can transform the Sdata's address from EApp to SM by adding the ERASE CALL to SM. However, it seem that Eapp' address space is different from the SM's. Is it possible to accesss Eapp's Sdata in SM ? What exactly is  the EApp address Space ? Shall I change the Sdata's address to pmp address space first?

**Comment by dayeol** [comment]
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/keystone-enclave-forum/zNHz4rvO76k

**Comment by dkohlbre** [comment]
Closing this for now, as discussion has concluded on the mailing list.
