### ISSUE TITLE
sifive builds don't update from overlay directory

### ISSUE THREAD

**Issue by dkohlbre** [keystone-enclave/keystone#182]
If you build using cmake -DLINUX_SIFIVE=y, any future modifications to the overlay/ directory will not be picked up in the resulting image. (Note that a non-sifive build works fine)

e.g.

mkdir build; cd build
cmake ../
make
./scripts/run-qemu.sh *check files in root, no file $foo*
touch overlay/root/$foo
make
./scripts/run-qemu.sh *check files in root, $foo found*

vs

mkdir build; cd build
cmake ../ -DLINUX_SIFIVE=y
make
./scripts/run-qemu.sh *check files in root, no file $foo*
touch overlay/root/$foo
make
./scripts/run-qemu.sh *check files in root, no $foo found*

I  suspect this is actually an issue with initramfs builds.

**Comment by dayeol** [comment]
@dkohlbre Plz link commits and close the issue if it was resolved. Thanks!

**Comment by dkohlbre** [comment]
This is a new issue and is unresolved.

**Comment by dkohlbre** [comment]
Ok, this occurs when initramfs is enabled, and is entirely related to how Linux gets built. Buildroot copies files/etc correctly, the initramfs data doesn't see changes.

**Comment by dkohlbre** [comment]
As a temporary fix, you can delete the entire `linux.build` dir, which will cause the next build to be much longer, but pickup new files from overlay

**Comment by dayeol** [comment]
I was able to figure out,

https://github.com/keystone-enclave/keystone/commit/e9fde5de05bee56bfe93a204422a825890ce5052#diff-af3b638bc2a3e6c650974192a53c7291R196

This change makes `linux` target not build vmlinux images again if they already exist.
Although `sysroot` and `overlay` are defined as dependencies in `add_custom_command`, it is not picked up.

**Comment by dayeol** [comment]
Closing
