### ISSUE TITLE
there is no branch of 37207f100227f4c34994db067b5fea3e383299ce0 in freedom

### ISSUE THREAD

**Issue by zhanghaojia123456** [keystone-enclave/keystone#184]
Hi, 
When I install key-stone for testing on VC70 FPGA. As described in KEYSTONE-FPGA.md, 

Sources for FPGA
Git clone and checkout the SiFive freedom:

$ git clone https://github.com/sifive/freedom.git
$ cd freedom/
$ git checkout 37207f100227f4c34994db067b5fea3e383299ce0
$ git submodule update --init --recursive

but there is no 37207f100227f4c34994db067b5fea3e383299ce0 branch in freedom project. What is the substitution to that?
Thanks

Jie

**Comment by dkohlbre** [comment]
It looks like that is just a typo, and the correct checkout is: 37207f100227f4c34994db067b5fea3e383299ce
I'll correct the document, thanks for pointing that out.

**Comment by dkohlbre** [comment]
fixed in https://github.com/keystone-enclave/keystone/pull/185
