### ISSUE TITLE
the question about make test？

### ISSUE THREAD

**Issue by wangaixue** [keystone-enclave/keystone#187]
After i finished the set_up.py. I build All Components and make test. I follow this command.
mkdir build
cd build
cmake ..
make
after finined the all components, I cd .. and source source.sh and cd build .
but make run_tests. there is a expection about this 

ssh_exchange_identification: read: Connection reset by peer
expect: spawn id exp6 not open
    while executing
"expect "# " { send "./tests.ke\r" }"
    (file "./scripts/test-qemu.sh" line 13)
1,5c1,19
< ssh_exchange_identification: read: Connection reset by peer
< expect: spawn id exp6 not open
<     while executing
< "expect "# " { send "./tests.ke\r" }"
<     (file "./scripts/test-qemu.sh" line 13)
---
> 
> # insmod keystone-driver.ko
> # ./tests.ke

so the result is output.log is not match the expected log

can you give me some advices?

my linux is centos. all submodule status is ok. I guess I can not ssh........in travis.sh.

**Comment by dkohlbre** [comment]
This looks like qemu is never starting, so the testing script cannot ssh into it to run commands.
Can you try:
1) Double checking that `make` succeeded. (You can safely run it again  while in `build/`
2) Starting qemu with the build image manually, to make sure it starts. (while in `build/` run: `scripts/run-qemu.sh`)

**Comment by wangaixue** [comment]
@dkohlbre  very thanks for your advices.
