### ISSUE TITLE
How to use on SD card

### ISSUE THREAD

**Issue by DeltaEnvy** [keystone-enclave/keystone#192]
If I want to use an SD card, do I need to modify it on lines 56 and 57 of bootloader.c, and if it needs to be modified, where is the corresponding compiled library file?

**Comment by dkohlbre** [comment]
Can you clarify what ypu mean by 'use with an SD card'?
If you are booting on a hifive unleashed the instructions for setting up the bootloader/etc are here: http://docs.keystone-enclave.org/en/dev/Getting-Started/Running-Keystone-on-Hardware.html

**Comment by DeltaEnvy** [comment]
I do as :http://docs.keystone-enclave.org/en/dev/Getting-Started/Running-Keystone-on-Hardware.html ,but it didn't boot,the hifive unleashed don't work, I want to know is there anything I can do to boot it. Here is my sd card  partition table.
/dev/sdb1         2048         67583         65536     32M   HiFIve Unleashed BBL
/dev/sdb2     264192   61849566   61585375   29.4G   Linux File System
/dev/sdb3       67584         69631           2048       1M   HiFive Unleashed FSBL

**Comment by dkohlbre** [comment]
A couple possibilities:
Are you on the `dev` branch?
Did you do a fully clean build? (Remove the entire old `build/` dir, etc)
Is the MSEL2 dipswitch set?

What is the exact failure you are seeing?

**Comment by DeltaEnvy** [comment]
I use the dev branch,and fully build,MSEL dipswitch set 1011,now,it can work,but will stop at 
[1.565817] --- [end Kernel panic - not syncing:Attempted to kill init! exit code =0x0000000b ]---

**Comment by dkohlbre** [comment]
@dayeol  can you confirm that the current `dev` branch works on a clean build for the FU540?
You may be running into the same issues as https://github.com/keystone-enclave/keystone/issues/189

**Comment by DeltaEnvy** [comment]
yes ,I can.Now,I think that the problem is not "end kernel panic ......",the problem is 
"Unable to handle kernel paging request at virtual address ffff_ffd0_0400_0000"
My commands are as follow:
cmake .. -DSM_PLATFORM=fu540
cmake .. -DLINUX_SIFIVE=y
make
make buildroot
make qemu
make linux
make sm
make bootrom
make driver
make tests
make image
./scripts/run-qemu.sh

Then I will get an error.
Do you know why this happens and how to solve it?
Thanks for your reply.
Best wishes.

**Comment by dayeol** [comment]
This issue is duplicated with #189. Please refer to the issue for further updates!
Closing
