### ISSUE TITLE
Problems with porting c++ code

### ISSUE THREAD

**Issue by zkh2018** [keystone-enclave/keystone#194]
Hello, I tested the migration of the existing c++ code on the docker provided by keystone, and found that several lines of code ran incorrectly. The code looked like this:
```
#include <iostream>
#include <sstream>
using namespace std;

int main()
{
  string str = "500";
  istringstream s(str);
  int value = 0;
  s >> value;
  cout << value << endl;
  return 0;
}
//riscv64-unknown-linux-gnu-g++ a.cpp -o a
// cp a to buildroot_overlay/root/
//./scripts/run-qemu.sh
//run a after login  
```
And 
The expected value=500，but actual value=-500.
How can I locate and solve this problem?

**Comment by dkohlbre** [comment]
Are you using Keystone to run this code?
Your example indicates that you are running not inside any Keystone related code.

Please include your git status, branch, etc.

**Comment by dkohlbre** [comment]
A quick note: out of curiosity I did reproduce what you are seeing.
It appears to be a compatibility issue between the c++ libs in the buildroot image and the toolchain. If you build your binaries with `-static` you won't see this behavior.

This appears to be unrelated to any Keystone code, but is instead a riscv toolchain + build image issue.

**Comment by zkh2018** [comment]
> A quick note: out of curiosity I did reproduce what you are seeing.
> It appears to be a compatibility issue between the c++ libs in the buildroot image and the toolchain. If you build your binaries with `-static` you won't see this behavior.
> 
> This appears to be unrelated to any Keystone code, but is instead a riscv toolchain + build image issue.

Thank you for your reply. I'll try build it with -static. 
In fact, this code will appear in the host side rather than in the enclave, so I want to test the correctness simply. In fact, I can directly migrate my code in the environment built according to this [document](https://risc-v-getting-started-guide.readthedocs.io/en/latest/linux-qemu.html), but this problem occurs in the docker environment provided by keystone, so it is not clear whether this problem is related to the version of the tool chain or Linux kernel or Linux system.

**Comment by zkh2018** [comment]
With the static compilation option, it can run correctly. Thank you for your help.
