### ISSUE TITLE
how to create the TEE like keystone in other platform?

### ISSUE THREAD

**Issue by wangaixue** [keystone-enclave/keystone#198]
I know this TEE is based with PMP. If I want to create the TEE like keystone in other platform, which has not pmp. If I should choose another address.

**Comment by dkohlbre** [comment]
Similar (security monitor/reference monitor) designs are out there. Notably the Komodo project (for ARM TZ) and Sanctum/MI-6 (for pre-PMP RISC-V).
We use github for bug tracking and feature tracking. If you want to discuss related designs or what Keystone would look like on other platforms please use the forum mailing list. (https://groups.google.com/forum/#!forum/keystone-enclave-forum)
