### ISSUE TITLE
Is RV32 M/U-only Systems be able to use keystone?

### ISSUE THREAD

**Issue by fanghuaqi** [keystone-enclave/keystone#209]
Hi there, I am wondering that when will keystone framework be ready for RV32 M/U only system, which run RTOS or baremetal service? 

Thanks
Huaqi

**Comment by dayeol** [comment]
@alexthomas1 and @ThaumicMekanism just started to work on M/U-only system, 
but we can't provide any specific date when it will be ready at this moment.
If you're interested in participating and contributing, please let me know.

**Comment by dayeol** [comment]
Closing.
