### ISSUE TITLE
FSBL Required?

### ISSUE THREAD

**Issue by jctullos** [keystone-enclave/keystone#210]
I'm using the modified FU540 FSBL for some of the FPGA builds to boot Keystone. On one of my builds, it'll take some extra work to get it added in. Is the SM specific code in the FSBL required for correct operation? I know the test keys are in the lds for riscv-pk, so it saves me some time if I don't have to implement the FSBL portion. 

Thank you!

**Comment by dayeol** [comment]
FSBL is required only for getting the valid remote attestation report.
Keystone framework itself doesn't include any hardware component such as secure booting (e.g., hardware hashes the boot image and then signs it) so we're basically emulating it via FSBL. The only thing FSBL does is to provide the security monitor key and then generate the report.

Attestation will not be valid until you have solid hardware that does all of these. We're "emulating" all of these process anyways, so if you're not interested in the attestation-related features, then you can just omit FSBL.

**Comment by dayeol** [comment]
Closing

**Comment by jctullos** [comment]
@dayeol That's great, thank you for the info!
