### ISSUE TITLE
Port new RISC-V SoC to keystone

### ISSUE THREAD

**Issue by fanghuaqi** [keystone-enclave/keystone#214]
Hi team,

1. I would like to know is there any more detailed steps about how to port a new RISC-V SoC to keystone except this page https://docs.keystone-enclave.org/en/latest/Contributing-to-Keystone/How-to-Contribute.html, I would like to port [Nuclei UX600](https://nucleisys.com/product.php?site=ux600) core to keystone, but I can't find more detailed documentation about how to do it.

2. I also observed that this keystone project is going to moving bbl to opensbi, when will it be ready to use?

3. If we have a M-U only RISC-V 32/64 system, will future keystone project support it, will it be a seperated project to consider about code size?

Thanks
Huaqi

**Comment by fanghuaqi** [comment]
By the way, we already supported opensbi for Nuclei UX600, will it be easier for porting keystone project?

Thanks
Huaqi

**Comment by dayeol** [comment]
Hello, I'm currently working on porting Keystone to OpenSBI.
It currently doesn't work, but you can follow up with this repo: https://github.com/keystone-enclave/sm
I can't provide when will it be ready, but it's my highest priority task right now, so hopefully, I can get it to work soon...

**Comment by fanghuaqi** [comment]
Hi @dayeol , thank you for your information, hopefully it will be soon.

**Comment by dayeol** [comment]
Will follow up in #212
