### ISSUE TITLE
keystone-linux-driver needs to be bumped for suiting firemarshal

### ISSUE THREAD

**Issue by yintianyu** [keystone-enclave/keystone#217]
When using in firemarshal, build linux failed for CROSS_COMPILE is not set

**Comment by dayeol** [comment]
Can you confirm that you're on `dev` branch?
It is bumped in `dev`
https://github.com/keystone-enclave/linux-keystone-driver/commit/3b1c9ce4dd0e9a1ef7b88d84648102b7f2671eac

**Comment by yintianyu** [comment]
> Can you confirm that you're on `dev` branch?
> It is bumped in `dev`
> [keystone-enclave/linux-keystone-driver@3b1c9ce](https://github.com/keystone-enclave/linux-keystone-driver/commit/3b1c9ce4dd0e9a1ef7b88d84648102b7f2671eac)

Sorry I was on master, I will close this issue.
