### ISSUE TITLE
Make sm only builds the Security Monitor

### ISSUE THREAD

**Issue by zchn** [keystone-enclave/keystone#252]
**Problem**

Currently, the `sm` target both builds the Security Monitor firmware and combines the sm firmware with the linux image. This introduces a dependecy from `sm` to `linux`, which makes dependency management very hard to do and causes problems like #251 . 

**Solution**
The `sm` target should focus on just building the security monitor, and the combination of the SM image and the linux image should be done at top level (e.g. inside the `image` target).

**Comment by zchn** [comment]
I'm not sure the effort is really worthy of the benefit now that #251 is fixed by not having `image` depends on `tests`. I looked into this and it is actually pretty hard to split them. I'm not planning to spend more time on this until a day when this is easy enough to do.

**Comment by dayeol** [comment]
We won't make this change. Closing the issue
