### ISSUE TITLE
configure returns errors about line, 4443 and 4444

### ISSUE THREAD

**Issue by ghost** [keystone-enclave/keystone#266]
**Describe the bug**
When I run configure, with or without options, it returns,

"checking whether make sets ${MAKE}... ./configure: eval: line 4443: unexpected EOF while looking for matching `"'
./configure: eval: line 4444: syntax error: unexpected end of file"

**Additional context**
I'm using windows terminal, more specifically with git bash and nuwens mingw. I'm trying to setup ncurses for use with powershell. I followed [this](https://github.com/mirror/ncurses/blob/master/README.MinGW) guide and used both the base and recommended options, I changed the mingw dir accordingly. I also tried with no config and still got the same errors.

**Comment by anydayeol** [comment]
I am sorry but I do not think Keystone can be built on Windows (e.g., mingw).

**Comment by dayeol** [comment]
I am sorry but I do not think Keystone can be built on Windows (e.g., mingw).
