### ISSUE TITLE
Multi-threaded enclave execution + ptrhead_create() system call

### ISSUE THREAD

**Issue by ncppd** [keystone-enclave/keystone#269]
Hello!

I am trying to understand how can I instantiate multiple threads for the same enclave, do you have any pointers how to do this?

Also, if an enclave can run in a multi-threaded context, is it feasible/easy to support the pthread_create() system call?

**Comment by anydayeol** [comment]
Hello, multi-threading is currently supported only in seL4, and not in Eyrie runtime.
Thus, libpthread is not supported, and the system call will fail.
Supporting multi threading had been discussed a long time ago, but had not been prioritized yet.

**Comment by dayeol** [comment]
Hello, multi-threading is currently supported only in seL4, and not in Eyrie runtime.
Thus, libpthread is not supported, and the system call will fail.
Supporting multi threading had been discussed a long time ago, but had not been prioritized yet.
