### ISSUE TITLE
could not insert module keystone-driver.ko

### ISSUE THREAD

**Issue by remyut** [keystone-enclave/keystone#270]
I have a  Linux debian 5.18.0-3-riscv64 #1 SMP Debian 5.18.14-1 (2022-07-23) riscv64 GNU/Linux on my QEMU machine.

I use the SDK to build the hello world enclave, all good. I can execute on buildroot when I do the make image. But i want to use a debian riscv64.

I cannot load the keystone driver:
root@debian:~# insmod keystone-driver.ko
[  115.914485] keystone_driver: module_layout: kernel tainted.
[  115.915777] Disabling lock debugging due to kernel taint
[  115.916673] keystone_driver: version magic '5.7.0-dirty SMP mod_unload riscv' should be '5.18.0-2-riscv64 SMP mod_unload modversions riscv'
insmod: ERROR: could not insert module keystone-driver.ko: Invalid module format

How can I modify the make image or the build to be able to load the keystone driver on my debian riscv64 distro?

Thanks for helping

**Comment by remyut** [comment]
i have clone the linux kernel v5.18 in the linux folder.
i have updated the conf/qemu_riscv64_virt_defconfig 
with:
# Kernel
BR2_LINUX_KERNEL=y
BR2_LINUX_KERNEL_CUSTOM_VERSION=y
BR2_LINUX_KERNEL_CUSTOM_VERSION_VALUE="5.18"

and i am getting: 
[ 90%] Building buildroot
make -s -C /home/remy/keystone/buildroot RISCV=/home/remy/keystone/riscv64 PATH=/home/remy/keystone/riscv64/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin O=/home/remy/keystone/build/buildroot.build
make[3]: Entering directory '/home/remy/keystone/buildroot'
linux/linux.mk:552: *** No kernel defconfig name specified, check your BR2_LINUX_KERNEL_DEFCONFIG setting.  Stop.

At first 
# Kernel
#BR2_LINUX_KERNEL=y //commenting out forced the kernel to compile, success
BR2_LINUX_KERNEL_CUSTOM_VERSION=y
BR2_LINUX_KERNEL_CUSTOM_VERSION_VALUE="5.18"

then i want to use it...

# Kernel
BR2_LINUX_KERNEL=y
BR2_LINUX_KERNEL_CUSTOM_VERSION=y
BR2_LINUX_KERNEL_CUSTOM_VERSION_VALUE="5.18"

Impossible to get buildroot to pass the compilation...
Any help?

**Comment by anydayeol** [comment]
We have not tested the current version with newer Linux kernel.
This is likely Linux & Buildroot compatibility issue, and is not related to Keystone.

Were you able to compile & build with 5.7 (which is provided in master)

**Comment by dayeol** [comment]
We have not tested the current version with newer Linux kernel.
This is likely Linux & Buildroot compatibility issue, and is not related to Keystone.

Were you able to compile & build with 5.7 (which is provided in master)

**Comment by remyut** [comment]
Thanks for the reply.
Yes I was able to compile and build with 5.7.

I am now trying to run the setup and compilation directly on a RISCV QEMU machine. Not sure if it works...Will post again.

**Comment by remyut** [comment]
Solution for now is to cross compile and load the binary of my program in the buildroot. Closing for now.
