### ISSUE TITLE
Skipping submodule 'riscv-gnu-toolchain'

### ISSUE THREAD

**Issue by yangshihao-arron** [keystone-enclave/keystone#280]
I use ubuntu18.04, when i use  ./fast-setup.sh,the following error occurs
Skipping submodule 'riscv-gnu-toolchain'
KEYSTONE_SDK_DIR is not set or present. Installing from /home/ysh/keystone/sdk
-- riscv64

**Comment by dayeol** [comment]
They are all expected messages, and are not errors.

If `KEYSTONE_SDK_DIR` is not set, it will assume that there is no SDK installed in your system, so it will install it from the default path.
