### ISSUE TITLE
Make fails if the qemu patch has been already applied 

### ISSUE THREAD

**Issue by ncppd** [keystone-enclave/keystone#304]
https://github.com/keystone-enclave/keystone/blob/05ebf3eb606ed9ee522f674700ac4fda2268860d/CMakeLists.txt#L14

In case the build directory is deleted, when I try to rebuild the project the build process fails due to the above command. 

This can be fixed by an older commit that added `|| true` at the end of the command in order to stop it from failing.

**Comment by its-luca** [comment]
I also encountered this problem
