### ISSUE TITLE
Using Keystone with OS other than Linux

### ISSUE THREAD

**Issue by its-luca** [keystone-enclave/keystone#312]
Hi,

I am trying to understand to which degree Keystone is entangled with Linux as the host operating system.
After browsing the READMEs and reading some code, it looks like the
`linux-keystone-driver`  is the only hard dependency (besides the use of some posix syscalls in the sdk).
Is this correct or am I missing something major here?

Cheers,
Luca

**Comment by clem844** [comment]
Hey Luca,

I'm not a maintainer of this project but it seems there is a FreeRTOS implementation.
The paper: [ERTOS: Enclaves in Real-Time Operating Systems](https://carrv.github.io/2021/papers/CARRV2021_paper_49_Thomas.pdf)
The code is in branch: [dev-embedded-freeRTOS](https://github.com/keystone-enclave/keystone/tree/dev-embedded-freeRTOS)

**Comment by alexthomas1** [comment]
Yes, the branch above is an example of using Keystone with FreeRTOS. It took some work to modify it, but feel free to use that branch as an example.

**Comment by its-luca** [comment]
Thanks
