### ISSUE TITLE
Memory related issues in Keystone

### ISSUE THREAD

**Issue by yangshihao-arron** [keystone-enclave/keystone#316]
**Describe the bug**
I encountered a problem when I implemented the SM password algorithm in Keystone. The problem is that I made an error when defining multiple unsigned long global array variables in eapp_native.c

### When I define the array like this, it is ok ###
```c
  #define u32 unsigned long
  u32 X[4]; 
  u32 MK[4]; 
  u32 TTA_1[32]; 
  int main(){
  }
```
### When I define the array like this, it is failed ###
```c
  #define u32 unsigned long
  u32 X[4]; 
  u32 MK[4]; 
  u32 TTA_1[4]; 
  int main(){
      //Error reported when using TTA_1
  }
```
**Screenshots or Error Log**
 [runtime] page fault at 0x101ae on 0xfffffffffffff842 (scause: 0xf)

**code environment**
Ubuntu18.04

**Comment by acaldaya** [comment]
which runtime version are you using?

**Comment by yangshihao-arron** [comment]
how to check runtime version,I only know the version of Keystone I use

**Comment by acaldaya** [comment]
the RT version depends on the Keystone version you are using.
However, recently the RT was integrated into the mono-repo so, the RT versioning got lost (ie. >= v1.2.1).

Nevertheless, I had issues with this [commit](https://github.com/keystone-enclave/keystone-runtime/commit/6958c3b00dd3a0a7ee1cef958bf3f8bfc67d2444) in the RT:

you could check if that commit is used in your setup and try to revert it.

**Comment by dayeol** [comment]
@grg-haas Could you please take a look at this issue?

**Comment by dayeol** [comment]
This might be related to the mmap issue #341

**Comment by dayeol** [comment]
Closing the issue -- please reopen when they reoccur.
