### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by drasko** [keystone-enclave/keystone#324]
**Describe the bug**
Website https://keystone-enclave.org/ is down

**Comment by dayeol** [comment]
Hi,

We're currently working on the fix.
Meanwhile, please use https://keystone-enclave.github.io/

Thanks!
Dayeol

**Comment by dayeol** [comment]
Turns out that GitHub somehow changed their custom domain verification.
Verified the domain again.
I had to contact Github support to release the domain (because it kept occupied even after verification).

It works as expected atm.
