### ISSUE TITLE
what is osm?

### ISSUE THREAD

**Issue by PengXuanyao** [keystone-enclave/keystone#340]
hi, I was reading through the code and came across a question. What is the meaning of OSM abbreviation here？

```
int osm_pmp_set(uint8_t perm)
{
  /* in case of OSM, PMP cfg is exactly the opposite.*/
  return pmp_set_keystone(os_region_id, perm);
}
```

why it says PMP cfg is exactly the opposite, but I can not find where is the opposite pmpcfg.

**Comment by philippgie** [comment]
From what I understand, *osm* refers to OS memory and pmpcfg to the *pmpcfg* to the PMP configuration. E.g., looking at `context_switch_to_enclave`, when switching to the enclave, the enclave memory is given all permissions and the opposite configuration is applied to the OS memory to guarantee isolation.  Vice versa for `context_switch_to_host`.

From the paper:
>During control-transfer to an enclave, the SM (for the
current core only): (a) enables PMP permission bits of the
relevant enclave memory region; and (b) removes all OS PMP
entry permissions to protect all other memory from the enclave. This allows the enclave to access its own memory and
no other regions. At a CPU context-switch to non-enclave,
the SM disables all permissions for the enclave region and
re-enables the OS PMP entry to allow default access from the
OS.

**Comment by PengXuanyao** [comment]
Thanks for your response. I think you are right that osm means os memory. It makes sense.
