### ISSUE TITLE
Driver: any user with access to `/dev/keystone_enclave` can access other users enclave's 

### ISSUE THREAD

**Issue by jarkkojs** [keystone-enclave/keystone#366]
EID's are not protected by file permissions, and thus users can cause undefined behavior to each other when figuring out other peer's EID. Also it is good to observe that a `struct file` instance is associated with an enclave with strong 1:1 binding. This is because EID is carried in `file->private_data`.

I have not analyzed that part in detail but it does look worrying that when unprivileged user pokes other's enclave can there be a corruption in the driver state. There's at least lot of potential of that happening sooner or later with this implementation.

So what should be done instead is to make things work in the granularity of file permissions. Anything you ever design in software has that ground-level for granularity because files are injected to all access control and integrity measurement frameworks.

This means literally not using eid as parameter in the ioctl. Only way at can be exposed in uapi that is acceptable for Linux is as read-only value.

Instead, you just store `struct enclave` instead to `file->private_data`

This how I solved similar situation in Intel SGX driver.

**Comment by jarkkojs** [comment]
Yeah, and also unintentional bugs in user space software could be the trigger here for the epic failure.

**Comment by jarkkojs** [comment]
I've drafted a solution [here](https://git.kernel.org/pub/scm/linux/kernel/git/jarkko/linux-riscv-keystone.git/tree/arch/riscv/kernel/keystone/ioctl.c?h=keystone).

**Comment by jarkkojs** [comment]
There is also a race condition concerning either multiple threads, or even multiple processes (i.e. `SCM_RIGHTS`), which share the file descriptor for an enclave.

As named, `unlocked_ioctl()` does not protect from concurrent access. Thus, some form of serialization must be in place.

I took the trivial path and implemented `O_NONBLOCK` alike semantics:

```c
	struct enclave *enclave = filep->private_data;
	size_t ioc_size;
	char data[512];
	long ret;

	if (!enclave)
		return -EIO;

	/* Mutually exclude concurrent threads: */
	if (test_and_set_bit(true, &enclave->busy)) {
		pr_info("%d busy\n", enclave->eid);
		return -EBUSY;
	}
```

Then in the end of `keystone_ioctl()` I placed:

```c
	default:
		ret = -ENOIOCTLCMD;
		break;
	}

	/* Copy back only on success: */
	if (!ret && copy_to_user((void __user *)arg, data, ioc_size))
		ret = -EFAULT;

err:
	clear_bit(true, &enclave->busy);
	return ret;
}
```

**Comment by jarkkojs** [comment]
You could consider also moving to use the driver patch inside of out-of-tree driver. I continue to update the kernel patch in `keystone` branch as I encounter issues. It is already superior to the out-of-tree driver both in performance (O(1) lookup) and security/privacy.

**Comment by dkohlbre** [comment]
FWIW, this is entirely within the Keystone threat model (and is why we didn't get around to doing it.)

Since the kernel is allowed to be malicious, it must be the case that the SM+enclave can handle any inputs, regardless of who they come from. Locking enclave access from the host side might be nice to have from the perspective of the _kernel's_ security model, but it won't affect the _Keystone_ security model.

If there is a bug in the runtime (and I'm very sure we have unknown bugs) then that needs to be the priority to fix.

Note that we do have a variety of utility functions/syscalls (e.g. accessing filesystems) in the RT right now that _do_ (mostly) trust the host/kernel side to do things correctly. These are for experimental purposes and not intended to hold security guarantees.

**Comment by jarkkojs** [comment]
> FWIW, this is entirely within the Keystone threat model (and is why we didn't get around to doing it.)
> 
> Since the kernel is allowed to be malicious, it must be the case that the SM+enclave can handle any inputs, regardless of who they come from. Locking enclave access from the host side might be nice to have from the perspective of the _kernel's_ security model, but it won't affect the _Keystone_ security model.

Even if Keystone can protect itself, it cannot protect kernel from driver bugs.

Here the issue is not the threat model of Keystone per se but having no any gate for concurrency in `keystone_ioctl()`, and invalid EID values for the caller causing undefined behavior. 

I get the argument that this driver does not need to be product quality, and that is fine. It still should be in the state that it is "somewhat" stable, i.e. does not crash if the crash can be easily prevented.

> If there is a bug in the runtime (and I'm very sure we have unknown bugs) then that needs to be the priority to fix.

I have squashed some other not as damaging bugs two but these are most disturbing **even** if just using Keystone driver for pure research:

1. 
   1. **Issue:** If due to a software bug in application, SDK or somewhere else wrong EID is passed, then that can cause spurious ioctl request sent to an arbitrary enclave without knowing
   2. **Fix:** Store `struct enclave` instance to `file->private_data`. By putting `eid` a hard binding between `eid` and the file is already created, meaning that in legit use this does not make the API more restricting. No change needed for uapi for the fix. The driver just ignores eid for the look-ups and grabs it from the private data.
2.
    1. **Issue:** If two threads call the ioctl simultaneously the drive state changes to an undefined state, meaning that memory can get corrupted.
    2. **Fix**: Add `unsigned long busy` to `struct enclave` and a guard in the beginning of the ioctl:

    ```
    /* Mutually exclude concurrent threads: */
    if (test_and_set_bit(true, &enclave->busy)) {
        pr_info("%d busy\n", enclave->eid);
        return -EBUSY;
    }

    ```

> Note that we do have a variety of utility functions/syscalls (e.g. accessing filesystems) in the RT right now that _do_ (mostly) trust the host/kernel side to do things correctly. These are for experimental purposes and not intended to hold security guarantees.

Well, it is pretty hard to be experimental with the Keystone project if it is super instable. With relatively modest fixes the driver could somewhat stable and predictable.

I could consider back-porting fixes for the out-of-tree driver, if you request so, and maybe that is actually a good first step, right?

The **major** benefit of kernel patch is that it is loaded at the kernel initialization and one promise of Keystone, and advantage compared to SGX, is that also kernel can use it for applications. OOT driver literally firewalls 50% of the potential research.

A bit side-tracked from about, and these are just learning questions (because could not find the answer from the documentation) but what is the thinking behind `epm_init()` implementation? I would like to understand:

1. When `GFP_HIGHUSER` is passed on to `__get_free_pages()`, kernel zeros `__GFP_HIGHMEM` before calling `alloc_pages()`. What is intended here?
2. 
    Where does this priority order is derived from:
    1. `__get_free_pages()`
    2. `dma_alloc_coherent()`
  
    Why opposite order is not preferred, i.e.
    1. `dma_alloc_coherent()`
    2. `__get_free_pages()`
    
    Or maybe these should have "xor" relation and depending on system either should be 
    picked? This code looks to me a bit confusing.

**Comment by jarkkojs** [comment]
PS. The use of in-kernel driver without actual modifications to the project is to add `BR2_LINUX_KERNEL_PATCH`, which can be used for additional kernel patches. Building out-of-tree driver does no harm as you just then don't load it when testing (as loading it is user space initiated process).

I'll keep my tree here in the foreseeable future: https://git.kernel.org/pub/scm/linux/kernel/git/jarkko/linux-riscv-keystone.git/

**Comment by jarkkojs** [comment]
And also my fixes do take still a shortcut but not as likely to cause any issues in research.

The race condition here is that if thread B is reads `enclave->busy` and thread A running on a different CPU core executes `destroy_enclave()`, this can lead to memory corruption and crash. Much more sparse but it is not like I'm over-productizing just raising the bar a bit.

The fix for this would be using `kref`: https://www.kernel.org/doc/Documentation/kref.txt (just mentioning for completeness). 

BR, Jarkko

**Comment by dkohlbre** [comment]
Aha, I misread your concern about the corruption, thought it was rt not kernel driver side.
All of these fixes (even if they were my previous rt reading) are still great and very welcome!
I just wanted to provide some context as to why the security model came into consideration.

I'll make sure we get back to your other questions in there.

**Comment by jarkkojs** [comment]
O

> Aha, I misread your concern about the corruption, thought it was rt not kernel driver side. All of these fixes (even if they were my previous rt reading) are still great and very welcome! I just wanted to provide some context as to why the security model came into consideration.
> 
> I'll make sure we get back to your other questions in there.

Great, I will backport them eventually. I just want to improve it enough that every day bugs do not cause crashes. E.g. a spurious value and stuff like that. It is more about developer experience of the project than anything else. I'll keep this issue open for the purpose.

**Comment by jarkkojs** [comment]
> I'll make sure we get back to your other questions in there.

It turned out to be nothing complicated! If there is block size suitable in buddy allocator, that is the first thing tried. Then if that fails the function tries allocation from CMA's pool using `dma_alloc_coherent()`.

Still sort of thinking maybe it would be for system balance if the first step did not exist. For me it looks like a bit like sort of mis-use of the buddy allocator. It would make so much more sense to have `dma_alloc_coherent()` call and leave it there.

This brings developer flexibility because then you tune how much you want for the main system and how much for enclaves, i.e. can pick a suitable memory partitioning, and enclave can't eat enough resources for the system completely halting.

I guess that is thought as an optimization but in kernel and drivers you optimize towards good balanced performance not for like "local maximum".

**Comment by jarkkojs** [comment]
OK so I get the use of buddy allocator given that CMA is optional but I think that the order you are using CMA and buddy allocator is 180 degrees wrong.

I guess the idea is that (or would make sense at least) that enclaves would live mostly in this area. So what could improve a lot already would be simply to reverse the order of use.

**Comment by jarkkojs** [comment]
One more thing that I denoted:

```	/* zero out */
	memset((void *)epm_vaddr, 0, PAGE_SIZE * count);
```

Is this necessary?

**Comment by dayeol** [comment]
^^ I think the reversing the order makes sense.

^ We do need to zero out somewhere in a trusted component, currently we're doing it inside the runtime.
Thus, I don't think we need memset to 0 in the driver.

**Comment by jarkkojs** [comment]
I'll close these bugs and open a new one for my driver soon. I ended up with about 500 lines of code with its own memory manager and no buddy allocator used (keeping kernel functional because its kernel's stash of resources).
