### ISSUE TITLE
Latest master does not compile

### ISSUE THREAD

**Issue by jarkkojs** [keystone-enclave/keystone#370]
Transcript:

```
>>> keystone-examples 20aef1a4a510b721 Syncing from source dir /home/jarkko/work/keystone-jarkkojs//examples
>>> keystone-examples 20aef1a4a510b721 Configuring
>>> keystone-examples 20aef1a4a510b721 Building
make[6]: *** [tests/CMakeFiles/eyrie-test-eyrie.dir/build.make:98: tests/runtime/src/eyrie-test-eyrie-stamp/eyrie-test-eyrie-downloa
d] Error 1
make[5]: *** [CMakeFiles/Makefile2:881: tests/CMakeFiles/eyrie-test-eyrie.dir/all] Error 2
make[6]: *** [hello-native/CMakeFiles/eyrie-hello-native-eyrie.dir/build.make:98: hello-native/runtime/src/eyrie-hello-native-eyrie-
stamp/eyrie-hello-native-eyrie-download] Error 1
make[5]: *** [CMakeFiles/Makefile2:407: hello-native/CMakeFiles/eyrie-hello-native-eyrie.dir/all] Error 2
make[6]: *** [hello/CMakeFiles/eyrie-hello-eyrie.dir/build.make:98: hello/runtime/src/eyrie-hello-eyrie-stamp/eyrie-hello-eyrie-down
load] Error 1
make[5]: *** [CMakeFiles/Makefile2:274: hello/CMakeFiles/eyrie-hello-eyrie.dir/all] Error 2
make[6]: *** [attestation/CMakeFiles/eyrie-attestor-eyrie.dir/build.make:98: attestation/runtime/src/eyrie-attestor-eyrie-stamp/eyri
e-attestor-eyrie-download] Error 1
make[5]: *** [CMakeFiles/Makefile2:540: attestation/CMakeFiles/eyrie-attestor-eyrie.dir/all] Error 2
make[4]: *** [CMakeFiles/Makefile2:203: CMakeFiles/examples.dir/rule] Error 2
make[3]: *** [Makefile:124: examples] Error 2
make[2]: *** [package/pkg-generic.mk:293: /home/jarkko/work/keystone-jarkkojs/build-generic64/buildroot.build/build/keystone-example
s-20aef1a4a510b721/.stamp_built] Error 2
make[1]: *** [Makefile:82: _all] Error 2
```

I tried to compile it with just typing make in the root directory because I did not see any update compilation instructions after the changes in the build procedure.

**Comment by grg-haas** [comment]
Thanks @jarkkojs , and apologies for this! This is addressed in #369 which we hope to merge soon. For now, please apply that patch manually -- you'll want to do a `BUILDROOT_TARGET=keystone-examples-dirclean make` before you run `make` again. This makes sure the `keystone-runtime` sources are correctly copied into the `keystone-examples` dependency directory.

**Comment by jarkkojs** [comment]
> Thanks @jarkkojs , and apologies for this! This is addressed in #369 which we hope to merge soon. For now, please apply that patch manually -- you'll want to do a `BUILDROOT_TARGET=keystone-examples-dirclean make` before you run `make` again. This makes sure the `keystone-runtime` sources are correctly copied into the `keystone-examples` dependency directory.

np thanks for the info!

**Comment by jarkkojs** [comment]
I'm looking forward to test this once it is compiling :-) 

https://git.kernel.org/pub/scm/linux/kernel/git/jarkko/linux-riscv-keystone.git/tree/arch/riscv/kernel/keystone.c?h=keystone-5.19.y

It is the full driver and in a single file. I could ask if this could be put to the `drivers/staging/tree` meaning that you would get it from the mainline tree.

**Comment by jarkkojs** [comment]
Staging does not mean that e.g. API needs to be final. See: https://lwn.net/Articles/324279/

**Comment by jarkkojs** [comment]
@grg-haas I now get it compile with `BUILDROOT_TARGET=keystone-examples-dirclean make`. Last time I tried it did not work but I guess my build was not fully clean so can close this. Thank you.
