### ISSUE TITLE
Problem building "Testing Keystone with QEMU" example, g++ compiler missing

### ISSUE THREAD

**Issue by SimuIacron** [keystone-enclave/keystone#421]
**Describe the bug**
I'm following the "Testing Keystone with QEMU" example in the docs (https://docs.keystone-enclave.org/en/latest/Getting-Started/Running-Keystone-with-QEMU.html). I installed all the dependencies, stated in the instruction. In step 1.2.1.3.1 I encounter a problem when building with the default settings (Please note, that this is the output, if I run make again after a failed build attempt, the first make console output also contained the previous successful build steps.)
`make -j$(nproc)` fails with the following output:

```

mkdir -p /opt/keystone//build-generic64/overlay
 >>>  (INF) Configuring Buildroot with qemu_riscv64_virt_defconfig
make -C /opt/keystone//buildroot O=/opt/keystone//build-generic64/buildroot.build BR2_EXTERNAL=/opt/keystone//overlays/keystone qemu_riscv64_virt_defconfig
make[1]: Entering directory '/opt/keystone/buildroot'
  GEN     /opt/keystone/build-generic64/buildroot.build/Makefile
#
# configuration written to /opt/keystone/build-generic64/buildroot.build/.config
#
make[1]: Leaving directory '/opt/keystone/buildroot'
echo "BR2_ROOTFS_OVERLAY=\"/opt/keystone//build-generic64/overlay \"" >> /opt/keystone//build-generic64/buildroot.build/.config
echo "BR2_CCACHE_DIR=/root/.buildroot-ccache" >> /opt/keystone//build-generic64/buildroot.build/.config
 >>>  (INF) Building Buildroot
set -o pipefail ; make -C /opt/keystone//buildroot O=/opt/keystone//build-generic64/buildroot.build BR2_EXTERNAL=/opt/keystone//overlays/keystone all 2>&1 | \
            tee /opt/keystone//build-generic64/build.log | LC_ALL=C grep -of scripts/grep.patterns
>>> host-keystone-sdk aebd8e585da22892 Configuring
make[2]: *** [package/pkg-generic.mk:283: /opt/keystone/build-generic64/buildroot.build/build/host-keystone-sdk-aebd8e585da22892/.stamp_configured] Error 1
make[1]: *** [Makefile:82: _all] Error 2
make: *** [Makefile:93: buildroot] Error 2
```

Inspecting the build.log in /opt/keystone/build-generic64 gives the following error (The following are only the last lines of the build.log):

```

CMake Error at macros.cmake:68 (message):
  Check for working C compiler:
  /opt/keystone/build-generic64/buildroot.build/host/bin/riscv64-buildroot-linux-gnu-g++
  -- not working
Call Stack (most recent call first):
  macros.cmake:49 (check_compiler)
  CMakeLists.txt:48 (use_riscv_toolchain)


-- Configuring incomplete, errors occurred!
See also "/opt/keystone/build-generic64/buildroot.build/build/host-keystone-sdk-aebd8e585da22892/CMakeFiles/CMakeOutput.log".
make[2]: *** [package/pkg-generic.mk:283: /opt/keystone/build-generic64/buildroot.build/build/host-keystone-sdk-aebd8e585da22892/.stamp_configured] Error 1
make[1]: *** [Makefile:82: _all] Error 2
make[1]: Leaving directory '/opt/keystone/buildroot'
```

Apparently the "riscv64-buildroot-linux-gnu-g++" compiler is missing. Checking the folder " /opt/keystone/build-generic64/buildroot.build/host/bin/" indeed shows that the compiler is missing. 

I have both gcc and g++ installed in /usr/bin if that information is of any help.
I also tried to install keystone both in a directory which needs sudo rights (/opt) and in my /home/$USER directory, both resulting in the same problem.

**Build Failure**
If you ran into build problems, please add this information
(1) Results of `git submodule status`
 c92cc8796ed951f0604e9272677a9cdfcd93680f buildroot (2023.02.2)
 cb35d1dba01da51b1489fb109f1b5598bd655267 overlays/keystone/board/cva6/cva6-sdk (v0.3.0-16-gcb35d1d)
 132d25d51d6b9d14ae59f949c769e0e1a53101c5 overlays/microchip (linux4microchip-2023.04-9-g132d25d)
 f615c3f3e78b9fd60f4803b823b49e55420a36ce runtime/test/cmocka (cmocka-1.1.5-27-gf615c3f)

(2) Your Linux distribution
Ubuntu 22.04.4 LTS
(3) The branch you're working on
master

**Comment by SimuIacron** [comment]
I recreated the error using docker to make sure it was not my system setup. Please note that I added the dependencies ca-certificates and openssh-client for the compilation to run until the error.

# Use a base image with necessary tools installed
FROM ubuntu:latest

ENV DEBIAN_FRONTEND=noninteractive

# Install required packages
RUN apt update && \
    apt install -y --no-install-recommends ca-certificates openssh-client \
    autoconf automake autotools-dev bc \
    bison build-essential curl expat jq libexpat1-dev flex gawk gcc git \
    gperf libgmp-dev libmpc-dev libmpfr-dev libtool texinfo tmux \
    patchutils zlib1g-dev wget bzip2 patch vim-common lbzip2 python3 \
    pkg-config libglib2.0-dev libpixman-1-dev libssl-dev screen \
    device-tree-compiler expect makeself unzip cpio rsync cmake ninja-build p7zip-full && \
    rm -rf /var/lib/apt/lists/*

# Clone the repository
RUN git clone --recurse-submodules https://github.com/keystone-enclave/keystone.git

# Set the working directory
WORKDIR /keystone

# Build the project
RUN KEYSTONE_PLATFORM=generic KEYSTONE_BITS=64 BUILDROOT_CONFIGFILE=qemu_riscv64_virt_defconfig BUILDROOT_TARGET=all make -j$(nproc)

# Run the project
CMD ["make", "run"]

**Comment by playasmegumin** [comment]
I met the same problem and now I have solved it.
You should open Buildroot Configuration through the same way you run the "make" command, like this:
```shell
#!/bin/sh
export KEYSTONE_PLATFORM=generic
export KEYSTONE_BITS=32
export BUILDROOT_CONFIGFILE=qemu_riscv32_virt_defconfig
export BUILDROOT_TARGET="all"

# make -j128
make buildroot-configure
```
Then buildroot would show you a TUI to configure like this:
<img width="1180" alt="图片" src="https://github.com/keystone-enclave/keystone/assets/26794587/2e5ab5ad-b2e7-4dde-a3b3-96a71b8b0036">
Select `Toolchain` and switch to `[ ] Enable C++ support` under `*** GCC OPtions ***`. Press <Y> to toggle this option and save the change.
After that, you should launch a `make clean all` to rebuild the whole project according to Buildroot's document. For example:
```shell
#!/bin/sh
export KEYSTONE_PLATFORM=generic
export KEYSTONE_BITS=32
export BUILDROOT_CONFIGFILE=qemu_riscv32_virt_defconfig
export BUILDROOT_TARGET="clean all"

make -j128
# make buildroot-configure
```

**Comment by SimuIacron** [comment]
This works for me, if I set "make -j1". Not sure why it fails when building in parallel.
