### ISSUE TITLE
Page fault when freeing memory

### ISSUE THREAD

**Issue by shimunn** [keystone-enclave/keystone#459]
**Describe the bug**
Calling `free` results in an pagefault

**Screenshots or Error Log**
```
[runtime] page fault at 0x1030 on 0x4000 (scause: 0xf)
```

**Additional context**

I've adapted the `malloc.c` test to allocate an larger area and added an call to `free()`:
```c
void EAPP_ENTRY eapp_entry(){
  int arg;
  int* ptr = (int*) malloc(sizeof(int) *  64);
  for(int i = 0; i < 1024; i++) {
  	ptr[i] = i % 42;
  }
  arg = ptr[63];
  free(ptr);

  EAPP_RETURN(arg);
}
```

**Comment by grg-haas** [comment]
Hi @shimunn! It seems that you are allocating space for 64 ints:

```
int* ptr = (int*) malloc(sizeof(int) *  64);
```

But then writing 1024 ints into this space:

```
for(int i = 0; i < 1024; i++) {
```

This probably has the effect of significantly corrupting heap metadata, causing the later `free()` to fault. I would try either allocating more memory or writing less ints.
