### ISSUE TITLE
Watchdog timers for scheduling and switching

### ISSUE THREAD

**Issue by dkohlbre** [keystone-enclave/keystone#46]
Currently, enclaves have the ability to simply never exit while running.

We want the following behavior:

A scheduling (timer) interrupt from the OS may arrive to the runtime.
The runtime is expected to save state and context switch out.
The sm is expected to enforce a timeout on this context switch, and kill the enclave if it does not save and exit expediently.

This will require (at least):
 - Updating the timer interrupt handling on entering an enclave to be accurate to the scheduling timer interrupt from the OS, and inform the sm.
 - Updating the sm to start a watchdog timer that is handled by the sm.

**Comment by dayeol** [comment]
This issue has been resolved by #151, though the design is not exactly the same as described in the issue.
The SM undelegates all interrupts from enclave, and this will be the default for a better security.
In the future, the SM will be able to selectively delegate/route interrupts using platform interrupt controller.
