### ISSUE TITLE
Roadmap document is gone

### ISSUE THREAD

**Issue by sbellem** [keystone-enclave/keystone#463]
The roadmap document linked in the readme, https://docs.google.com/document/d/1E-982564GvOcWzdCqM7TXCJV_7uWy2F8NiwglWorjFA/edit#heading=h.xa3pe84ubay4, is gone.

**Comment by dayeol** [comment]
Hello, the owner of the document has hit the Google Drive storage limit, so I moved the document here. 

https://docs.google.com/document/d/1AxT0w6NCtfvZcFE1wbZAkAODftqRYhpHaj63mvnQQqA/edit?usp=sharing
