### ISSUE TITLE
[Issue] No easy method to move custom eapps to the HiFive build.

### ISSUE THREAD

**Issue by ThaumicMekanism** [keystone-enclave/keystone#59]
Currently the only way to do this is via: 

> copying keystone-demo bins into sdk/bin and running hifive make, or by copying them into hifive-work/buildroot_initramfs/target/root/
and then running hifive make
(Credit to @dkohlbre for this current solution)

Though an inclusion of this in a make file would make it easier for developers.

**Comment by dayeol** [comment]
I believe this is not mandatory. You can always send the files over ssh.
Closing the issue until we need it
