### ISSUE TITLE
Correct type definitions to not use reserved naming

### ISSUE THREAD

**Issue by dkohlbre** [keystone-enclave/keystone#76]
We are using a lot of `_t` types we created. These are reserved names.
Current proposal is to move to `_kt` for keystone-type.

Should we require ALL keystone types to have this naming convention? (Or just typedefs of non-struct types)

**Comment by dayeol** [comment]
@dkohlbre is this resolved?

**Comment by dkohlbre** [comment]
Not quite:
https://github.com/keystone-enclave/linux-keystone-driver/pull/15
https://github.com/keystone-enclave/keystone-runtime/pull/16 (waiting on this to do the sdk pr)
