### ISSUE TITLE
Make Enclave Runner Configurable with command-line Options

### ISSUE THREAD

**Issue by dayeol** [keystone-enclave/keystone#80]
The only runner we have in sdk is `test-runner`, which is shared by all tests (as well as SeL4 booting).
There're several configurable parameters such as freemem size, untrusted memory (shared buffer) size, and so on.
We want them to be configurable by passing command line arguments.
This issue is also related to the measurement utility #74

**Comment by dkohlbre** [comment]
When this happens, we should add additional tests to the travis as well, test various configurations/etc (possibly build multiple eyrie-rts as well and test those configurations)
