### ISSUE TITLE
No access rights

### ISSUE THREAD

**Issue by OSer916** [keystone-enclave/keystone#9]
I clone the source, and do "git submodule init", "git submodule update" : 

git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

**Comment by dayeol** [comment]
Hi,

We're using SSH (git@github.com) instead of HTTPS (https://github.com) for the submodules,
so you probably need to register your public key (`~/.ssh/id_rsa.pub`) to your github account.

I think this might help:
https://help.github.com/articles/adding-a-new-ssh-key-to-your-github-account/

**Comment by dayeol** [comment]
We're going to switch the submodule URLs from ssh to https 
@dkohlbre, can you do this when you're ready?
