### ISSUE TITLE
Fixing sm hash calculation

### ISSUE THREAD

**Issue by mcd500** [keystone-enclave/keystone#93]
I temporary pushed it to my repo, since the keystone changes are not merged to the sifive/freedom-u540-c000-bootloader at the moment.
Do you mind merging this to your repo?

https://github.com/mcd500/keystone-freedom-u540-c000-bootloader/pull/1/commits/bcc8b8497eef77dfd058e41e6ef825158400904e

With the commit https://github.com/keystone-enclave/freedom-u540-c000-bootloader/commit/3fe4313c5952195d8d21e93ea2cca9b3c41ec4e4 which is fixing
the starting address of the payload, then it was calculating the hash crossing the boundary of sm area and payload area.
Fixing the length accordingly to prevent having different hash values for just loading different kernel.

We are currently porting zsbl and fsbl on fpga to make them build and run keystone on both fpgas and sifive Unleashed. Please give us some time to cleaning and testing them in the bellow link to be ready for pull requests.
https://github.com/mcd500/freedom/tree/vc707-zsbl-try

**Comment by dkohlbre** [comment]
Good catch!
Would you be willing to open a PR for the bootloader? Easier to keep track of that way.

For the porting effort, we've been successfully running on the Unleashed (FU540) without issues, and we've also been able to run on F1 instances using FireSim setups. What issues have you run into on vc707s (if any)?

**Comment by mcd500** [comment]
I initially wanted to make a pull request yesterday. 

However, 
https://github.com/keystone-enclave/freedom-u540-c000-bootloader
is a fork from the 
https://github.com/sifive/freedom-u540-c000-bootloader.
And I already forked the 
https://github.com/sifive/freedom-u540-c000-bootloader
to my repo and it is here:
https://github.com/mcd500/freedom-u540-c000-bootloader

To make the pull request for the keystone fsbl then I have to make the fork from
https://github.com/keystone-enclave/freedom-u540-c000-bootloader
but the github does not allow me to fork to my repo since there are `freedom-u540-c000-bootloader` already exist from the 
https://github.com/sifive/freedom-u540-c000-bootloader

To make the pull request, I have to try seting multiple origins in my single repo and fetch them and try whether it works well on github or not. I will try it later.

**Comment by mcd500** [comment]
We are trying to boot keystone from building single sources on github of the keystone-enclave for all  Unleashed (FU540), firesim, and FPGAs (currently we are stating from Xilins vc707).
We have able to boot keystone on vc707 after heavily customizing the sources and I have posted here.
https://github.com/sifive/freedom/issues/119

However it does not boot on fpga without customizing the source for both keystone side and fpga side at the moment, which we would like to avoid, since it will require us to porting keystone to fpga every time when the branch of keystone go ahead.

The current bootrom prepared for fpga at 
https://github.com/sifive/freedom/tree/master/bootrom
do not read partitions in SD card. It treat as a raw device and reading binary from the first sector.
So it require making fsbl, bbl, kernel, dtb, initramfs on one single image and dding to sd.
We are trying to port zsbl on fpga, and there are several attempt under the following directly.
https://github.com/mcd500/freedom/tree/vc707-zsbl-try/bootrom

The link bellow boots fine and read partitions of sd card and load keystone version of fsbl successfully but the code is not based on zsbl, instead from the original sdboot adding reading the partition just we wanted to make something work first.
https://github.com/mcd500/freedom/tree/vc707-zsbl-try/bootrom/sdboot-gpt

This is the attempt to built zsbl from single source to boot on fpga read fsbl partition in SD card as well which will make everybody easy to maintenance in the future but not booting yet on fpga. I will describe which part is not finished some time later.
https://github.com/mcd500/freedom-u540-c000-bootloader/tree/53f8d4320e3cf897b873e852c4ec1a356b8f93ec

As mentioned in https://github.com/sifive/freedom/issues/119, the address of uart, spi, gpio differs between Unleashed and fpga which do not look like they really have to be different, so this have to be merged at sifive freedom repo first, which I have not made the pull request yet. We are all busy. hehe.

Next is that,
the keystone version of fsbl do not boot on FPGA and started from customizing the source but it boots on FPGA only now and do not boot on Unleashed anymore. 
https://github.com/mcd500/keystone-freedom-u540-c000-bootloader/tree/thuc-branch
The fsbl initialize many peripherals do not exist in FPGA and dtb must be used which generated during building FPGA.

So started to make the fsbl bootable on both Unleashed and FPGA but not quite tested yet.
https://github.com/mcd500/freedom-u540-c000-bootloader/blob/53f8d4320e3cf897b873e852c4ec1a356b8f93ec/Makefile

I will come back when I can focus them again later.

**Comment by dkohlbre** [comment]
Ah github problems, totally understand :)
I've pushed that size change.

**Comment by mcd500** [comment]
Thanks for merging the size change!

**Comment by dayeol** [comment]
@dkohlbre May I close this?

**Comment by mcd500** [comment]
Sorry forgot close this, just closed it now.
